### ISSUE TITLE
No option to use the L sticker of UBL for the corner buffer

### ISSUE THREAD

**Issue by mocliamtoh** [cahidenes/blindfolded-master#1]
The options are L***U***B,  U***B***L, and B***U***L. It uses the middle of those three sides, so there's no option to actually specify the left sticker on the corner buffer.

**Comment by cahidenes** [comment]
Actually, the buffer sticker is the first letter of the triplets. L sticker corresponds to LUB buffer. However, there was an error causing buffers to be interpreted as the same orientation every time. This should be fixed now.
Thanks for reporting the bug! Please verify that the bug is fixed and close the issue.

**Comment by mocliamtoh** [comment]
Looks fixed! Thanks for the update!
